use crate::model::{ApiEndpoint, ParamLocation};
use heck::ToSnakeCase;

const HEADER: &str = "// Auto-generated by sdk-gen — DO NOT EDIT\n\
// Draox Server Dart Client SDK\n\
import 'dart:convert';\nimport 'package:http/http.dart' as http;\n";

pub fn emit(endpoints: &[ApiEndpoint], base_url: &str) -> String {
    let mut out = String::from(HEADER);

    out.push_str(&format!("\nconst String _base = '{}';\nString? _authToken;\n\n", base_url));

    out.push_str(
        "Future<void> login(String username, String password) async {\n  \
         final uri = Uri.parse('$_base/api/auth/login');\n  \
         final res = await http.post(uri,\n      \
         headers: {'Content-Type': 'application/json'},\n      \
         body: jsonEncode({'username': username, 'password': password}));\n  \
         if (res.statusCode >= 400) throw Exception('Login failed: $\\{res.statusCode\\}');\n  \
         final body = jsonDecode(res.body) as Map<String, dynamic>;\n  \
         if (body['success'] != true) throw Exception('Login failed: unexpected response');\n  \
         _authToken = (body['data'] as Map<String, dynamic>)['token'] as String;\n}\n\n\
         Future<dynamic> _request(String method, String path, [Map<String, dynamic>? body]) async {\n  \
         final uri = Uri.parse('$_base$path');\n  \
         final headers = <String, String>{'Content-Type': 'application/json'};\n  \
         if (_authToken != null) headers['Authorization'] = 'Bearer $_authToken';\n  \
         http.Response res;\n  \
         switch (method) {\n    \
         case 'GET': res = await http.get(uri, headers: headers); break;\n    \
         case 'DELETE': res = await http.delete(uri, headers: headers); break;\n    \
         default:\n      \
         res = await http.post(uri, headers: headers, body: body != null ? jsonEncode(body) : null);\n  }\n  \
         if (res.statusCode >= 400) throw Exception('$method $path => $\\{res.statusCode\\}');\n  \
         return jsonDecode(res.body);\n}\n\n",
    );

    for ep in endpoints {
        let fn_name = ep.operation_id.to_snake_case();

        let path_params: Vec<_> = ep
            .params
            .iter()
            .filter(|p| p.location == ParamLocation::Path)
            .collect();

        let mut sig: Vec<String> = path_params
            .iter()
            .map(|p| format!("String {}", p.name))
            .collect();

        if ep.request_body.is_some() {
            sig.push("Map<String, dynamic>? body".into());
        }

        let mut runtime_path = ep.path.clone();
        for p in &path_params {
            runtime_path =
                runtime_path.replace(&format!("{{{}}}", p.name), &format!("${{{}}}", p.name));
        }

        let body_arg = if ep.request_body.is_some() { ", body" } else { "" };

        if let Some(summary) = &ep.summary {
            out.push_str(&format!("/// {}\n", summary));
        }

        out.push_str(&format!(
            "Future<dynamic> {fn}({sig}) async {{\n  \
             return _request('{}', '{}'{}); \n}}\n\n",
            ep.method,
            runtime_path,
            body_arg,
            fn = fn_name,
            sig = sig.join(", "),
        ));
    }

    out
}
