use crate::model::ApiEndpoint;
use heck::ToUpperCamelCase;

const HEADER: &str = "// Auto-generated by sdk-gen — DO NOT EDIT\n\
// Draox Server TypeScript Client SDK\n";

pub fn emit(endpoints: &[ApiEndpoint], base_url: &str) -> String {
    let mut out = String::from(HEADER);

    out.push_str(&format!(
        "\nconst BASE_URL = '{}';\n\n",
        base_url
    ));

    out.push_str(
        "let _authToken: string | null = null;\n\n\
         export async function login(username: string, password: string): Promise<void> {\n  \
         const res = await fetch(`${BASE_URL}/api/auth/login`, {\n    \
         method: 'POST',\n    \
         headers: { 'Content-Type': 'application/json' },\n    \
         body: JSON.stringify({ username, password }),\n  });\n  \
         if (!res.ok) throw new Error(`Login failed: ${res.status}`);\n  \
         const body = await res.json() as { success: boolean; data: { token: string } };\n  \
         if (!body.success || !body.data?.token) throw new Error('Login failed: unexpected response');\n  \
         _authToken = body.data.token;\n}\n\n\
         async function request<T>(method: string, path: string, body?: unknown): Promise<T> {\n  \
         const headers: Record<string, string> = { 'Content-Type': 'application/json' };\n  \
         if (_authToken) headers['Authorization'] = `Bearer ${_authToken}`;\n  \
         const res = await fetch(`${BASE_URL}${path}`, {\n    \
         method,\n    \
         headers,\n    \
         body: body ? JSON.stringify(body) : undefined,\n  });\n  \
         if (!res.ok) throw new Error(`${method} ${path} → ${res.status}`);\n  \
         return res.json() as Promise<T>;\n}\n\n",
    );

    for ep in endpoints {
        let fn_name = ep.operation_id.to_upper_camel_case();
        let fn_name = lowercase_first(&fn_name);

        let path_params: Vec<_> = ep
            .params
            .iter()
            .filter(|p| p.location == crate::model::ParamLocation::Path)
            .collect();

        let query_params: Vec<_> = ep
            .params
            .iter()
            .filter(|p| p.location == crate::model::ParamLocation::Query)
            .collect();

        let mut sig_parts: Vec<String> = path_params
            .iter()
            .map(|p| format!("{}: string", p.name))
            .collect();

        if !query_params.is_empty() {
            let qp: Vec<_> = query_params
                .iter()
                .map(|p| {
                    if p.required {
                        format!("{}: string", p.name)
                    } else {
                        format!("{}?: string", p.name)
                    }
                })
                .collect();
            sig_parts.extend(qp);
        }

        if ep.request_body.is_some() {
            sig_parts.push("body: Record<string, unknown>".into());
        }

        let sig = sig_parts.join(", ");

        // Build runtime path
        let mut runtime_path = ep.path.clone();
        for p in &path_params {
            runtime_path = runtime_path.replace(&format!("{{{}}}", p.name), &format!("${{{}}}", p.name));
        }

        // Build query string
        let qs = if query_params.is_empty() {
            String::new()
        } else {
            let pairs: Vec<_> = query_params
                .iter()
                .map(|p| format!("'{}=' + {}", p.name, p.name))
                .collect();
            format!(" + '?' + [{}].filter(Boolean).join('&')", pairs.join(", "))
        };

        let body_arg = if ep.request_body.is_some() { ", body" } else { "" };

        if let Some(summary) = &ep.summary {
            out.push_str(&format!("/** {} */\n", summary));
        }

        out.push_str(&format!(
            "export async function {fn}({sig}): Promise<unknown> {{\n  \
             return request('{}', `{}{}`{});\n}}\n\n",
            ep.method,
            runtime_path,
            qs,
            body_arg,
            fn = fn_name,
            sig = sig,
        ));
    }

    out
}

fn lowercase_first(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
    }
}
