//! Connection handoff protocol.
//!
//! A handoff is a two-phase operation:
//! 1. **Initiate** — the source session requests a transfer; the manager
//!    mints a time-limited token and records the pending handoff.
//! 2. **Complete** — the target session presents the token; the manager
//!    removes the pending record and returns the [`HandoffToken`] so the
//!    caller can migrate the connection.
//!
//! Tokens are UUIDs generated by [`uuid::Uuid::new_v4`].

use dashmap::DashMap;
use server_core::{ConnectionId, SessionId};
use std::time::{Duration, Instant};
use uuid::Uuid;

/// Describes a pending connection handoff.
#[derive(Debug, Clone)]
pub struct HandoffToken {
    /// The connection being transferred.
    pub connection_id: ConnectionId,
    /// The session that currently owns the connection.
    pub source_session: SessionId,
    /// The session that should receive the connection.
    pub target_session: SessionId,
    /// The one-time secret token string presented by the target.
    pub token: String,
    /// When this handoff was initiated.
    pub created_at: Instant,
    /// After this instant the handoff token is invalid.
    pub expires_at: Instant,
}

/// Manages pending connection handoffs.
pub struct HandoffManager {
    /// token string → HandoffToken
    pending: DashMap<String, HandoffToken>,
}

impl HandoffManager {
    /// Create a new, empty `HandoffManager`.
    pub fn new() -> Self {
        Self {
            pending: DashMap::new(),
        }
    }

    /// Initiate a handoff for `conn_id` from `source` to `target`.
    ///
    /// A fresh UUID token is generated and the handoff is recorded with an
    /// expiry of `now + ttl`. Returns the token string that the target
    /// session must present to [`complete`].
    pub fn initiate(
        &self,
        conn_id: ConnectionId,
        source: SessionId,
        target: SessionId,
        ttl: Duration,
    ) -> String {
        let token = Uuid::new_v4().to_string();
        let now = Instant::now();
        let handoff = HandoffToken {
            connection_id: conn_id,
            source_session: source,
            target_session: target,
            token: token.clone(),
            created_at: now,
            expires_at: now + ttl,
        };
        self.pending.insert(token.clone(), handoff);
        token
    }

    /// Complete a handoff by consuming the token.
    ///
    /// Returns the [`HandoffToken`] if the token exists and has not expired,
    /// or `None` if the token is unknown or expired (in which case the token
    /// is also removed to prevent replay).
    pub fn complete(&self, token: &str) -> Option<HandoffToken> {
        let (_, handoff) = self.pending.remove(token)?;
        if Instant::now() > handoff.expires_at {
            // Token existed but has expired — discard it.
            return None;
        }
        Some(handoff)
    }

    /// Cancel a pending handoff by token.
    ///
    /// Returns `true` if a pending handoff was found and removed, `false`
    /// otherwise.
    pub fn cancel(&self, token: &str) -> bool {
        self.pending.remove(token).is_some()
    }

    /// Remove all handoffs whose `expires_at` has passed.
    ///
    /// Should be called periodically by a background task to prevent memory
    /// accumulation from un-completed handoffs.
    pub fn cleanup_expired(&self) {
        let now = Instant::now();
        self.pending.retain(|_token, h| now <= h.expires_at);
    }
}

impl Default for HandoffManager {
    fn default() -> Self {
        Self::new()
    }
}

// ────────────────────────────────────────────────────────
// Tests
// ────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_initiate_and_complete() {
        let hm = HandoffManager::new();
        let conn = ConnectionId::new();
        let src = SessionId::new();
        let tgt = SessionId::new();

        let token = hm.initiate(conn.clone(), src.clone(), tgt.clone(), Duration::from_secs(30));
        assert!(!token.is_empty());

        let result = hm.complete(&token);
        assert!(result.is_some());
        let handoff = result.unwrap();
        assert_eq!(handoff.connection_id, conn);
        assert_eq!(handoff.source_session, src);
        assert_eq!(handoff.target_session, tgt);
    }

    #[test]
    fn test_complete_removes_token() {
        let hm = HandoffManager::new();
        let token = hm.initiate(
            ConnectionId::new(),
            SessionId::new(),
            SessionId::new(),
            Duration::from_secs(30),
        );

        hm.complete(&token);
        // Second complete should return None (token consumed).
        assert!(hm.complete(&token).is_none());
    }

    #[test]
    fn test_complete_expired_token_returns_none() {
        let hm = HandoffManager::new();
        // TTL of 0 expires immediately.
        let token = hm.initiate(
            ConnectionId::new(),
            SessionId::new(),
            SessionId::new(),
            Duration::from_millis(0),
        );

        // Even a tiny sleep ensures expiry.
        std::thread::sleep(Duration::from_millis(2));
        assert!(hm.complete(&token).is_none());
    }

    #[test]
    fn test_cancel_pending_handoff() {
        let hm = HandoffManager::new();
        let token = hm.initiate(
            ConnectionId::new(),
            SessionId::new(),
            SessionId::new(),
            Duration::from_secs(60),
        );

        assert!(hm.cancel(&token));
        assert!(!hm.cancel(&token)); // Already removed.
        assert!(hm.complete(&token).is_none());
    }
}
