/// SQL `CREATE TABLE IF NOT EXISTS` statements for all clan-related tables.
///
/// Each entry is `(table_name, create_statement)`.  The statements use
/// portable SQL that is accepted by SQLite, PostgreSQL, and MySQL when run
/// through `sqlx` migrations.
///
/// Column types follow the lowest-common-denominator dialect:
/// - `TEXT` for strings / UUIDs / identifiers
/// - `INTEGER` for booleans (0/1) and counts
/// - `TIMESTAMP WITH TIME ZONE` for UTC datetimes
///
/// All tables use natural TEXT primary keys (the same `ClanId`/`DivisionId`
/// values generated by the in-memory managers) so that the database and
/// in-memory state can be trivially reconciled.
pub const CLAN_SCHEMAS: &[(&str, &str)] = &[
    // ── clans ───────────────────────────────────────────────────────────────
    (
        "clans",
        "CREATE TABLE IF NOT EXISTS clans (
            id          TEXT        PRIMARY KEY,
            name        TEXT        NOT NULL,
            tag         TEXT        NOT NULL DEFAULT '',
            description TEXT        NOT NULL DEFAULT '',
            owner_id    TEXT        NOT NULL,
            max_members INTEGER     NOT NULL DEFAULT 100,
            icon_url    TEXT        NOT NULL DEFAULT '',
            tags        TEXT        NOT NULL DEFAULT '[]',   -- JSON array
            settings    TEXT        NOT NULL DEFAULT '{}',   -- JSON object
            created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )",
    ),
    // ── clan_members ────────────────────────────────────────────────────────
    (
        "clan_members",
        "CREATE TABLE IF NOT EXISTS clan_members (
            clan_id     TEXT    NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
            client_id   TEXT    NOT NULL,
            role        TEXT    NOT NULL DEFAULT 'recruit', -- owner|officer|member|recruit
            joined_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (clan_id, client_id)
        )",
    ),
    // ── clan_bans ───────────────────────────────────────────────────────────
    (
        "clan_bans",
        "CREATE TABLE IF NOT EXISTS clan_bans (
            clan_id     TEXT    NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
            client_id   TEXT    NOT NULL,
            banned_by   TEXT    NOT NULL,
            banned_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            reason      TEXT,
            PRIMARY KEY (clan_id, client_id)
        )",
    ),
    // ── clan_invites ────────────────────────────────────────────────────────
    (
        "clan_invites",
        "CREATE TABLE IF NOT EXISTS clan_invites (
            code        TEXT    PRIMARY KEY,
            clan_id     TEXT    NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
            created_by  TEXT    NOT NULL,
            created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            expires_at  TIMESTAMP WITH TIME ZONE,
            max_uses    INTEGER,
            use_count   INTEGER NOT NULL DEFAULT 0
        )",
    ),
    // ── clan_divisions ──────────────────────────────────────────────────────
    (
        "clan_divisions",
        "CREATE TABLE IF NOT EXISTS clan_divisions (
            id          TEXT    PRIMARY KEY,
            clan_id     TEXT    NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
            name        TEXT    NOT NULL,
            description TEXT,
            leader      TEXT,           -- client_id, nullable
            created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )",
    ),
    // ── clan_division_members ───────────────────────────────────────────────
    (
        "clan_division_members",
        "CREATE TABLE IF NOT EXISTS clan_division_members (
            division_id TEXT    NOT NULL REFERENCES clan_divisions(id) ON DELETE CASCADE,
            client_id   TEXT    NOT NULL,
            PRIMARY KEY (division_id, client_id)
        )",
    ),
    // ── clan_channels ───────────────────────────────────────────────────────
    (
        "clan_channels",
        "CREATE TABLE IF NOT EXISTS clan_channels (
            id           TEXT    PRIMARY KEY,
            clan_id      TEXT    NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
            name         TEXT    NOT NULL,
            channel_type TEXT    NOT NULL DEFAULT 'custom',   -- general|officers|division|custom
            division_id  TEXT    REFERENCES clan_divisions(id) ON DELETE SET NULL,
            min_role     TEXT    NOT NULL DEFAULT 'recruit',  -- owner|officer|member|recruit
            created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )",
    ),
    // ── clan_alliances ──────────────────────────────────────────────────────
    (
        "clan_alliances",
        "CREATE TABLE IF NOT EXISTS clan_alliances (
            id          TEXT    PRIMARY KEY,
            clan_a      TEXT    NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
            clan_b      TEXT    NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
            status      TEXT    NOT NULL DEFAULT 'proposed',  -- proposed|active|rejected|dissolved
            proposed_by TEXT    NOT NULL,
            proposed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            accepted_at TIMESTAMP WITH TIME ZONE,
            dissolved_at TIMESTAMP WITH TIME ZONE
        )",
    ),
];

/// Return the `CREATE TABLE` SQL for a named table.
///
/// Convenience helper used in tests and migrations.
pub fn schema_for(table_name: &str) -> Option<&'static str> {
    CLAN_SCHEMAS
        .iter()
        .find(|(name, _)| *name == table_name)
        .map(|(_, sql)| *sql)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_expected_tables_present() {
        let expected = [
            "clans",
            "clan_members",
            "clan_bans",
            "clan_invites",
            "clan_divisions",
            "clan_division_members",
            "clan_channels",
            "clan_alliances",
        ];

        let defined: Vec<&str> = CLAN_SCHEMAS.iter().map(|(name, _)| *name).collect();

        for table in &expected {
            assert!(
                defined.contains(table),
                "missing schema for table '{table}'"
            );
        }
    }

    #[test]
    fn test_each_schema_contains_create_table() {
        for (table, sql) in CLAN_SCHEMAS {
            let sql_upper = sql.to_uppercase();
            assert!(
                sql_upper.contains("CREATE TABLE IF NOT EXISTS"),
                "schema for '{table}' must use CREATE TABLE IF NOT EXISTS"
            );
            // The table name must appear in the SQL
            assert!(
                sql_upper.contains(&table.to_uppercase()),
                "schema SQL for '{table}' does not mention the table name"
            );
        }
    }

    #[test]
    fn test_schema_for_helper() {
        // Known table returns Some
        let sql = schema_for("clans").expect("clans schema must exist");
        assert!(sql.contains("id") && sql.contains("name"));

        // Unknown table returns None
        assert!(schema_for("nonexistent_table").is_none());
    }
}
